spring.application.name=gofundme
server.port=${PORT:8080}

logging.level.root=ERROR
logging.level.com.securityapp.gofundme=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
server.error.include-message=never

# ===============================
# DATABASE (Aiven)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gofundme_clone?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ===============================
# STRIPE
# ===============================
stripe.api.key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
stripe.public.key=${STRIPE_PUBLIC_KEY:}

# ===============================
# MONCASH
# ===============================
moncash.client.id=${MONCASH_CLIENT_ID}
moncash.client.secret=${MONCASH_SECRET}
moncash.base.url=https://sandbox.moncashbutton.digicelgroup.com/Api

# ===============================
# EMAIL (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# GOOGLE OAUTH2
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${BASE_URL:http://localhost:8080}/login/oauth2/code/{registrationId}

# ===============================
# PLATFORM FEE
# ===============================
platform.fee.percentage=0.05

# ===============================
# SECURITY
# ===============================
payment.encryption.key=${PAYMENT_ENCRYPTION_KEY:}

# D\u00e9sactiver JSP
spring.mvc.view.prefix=
spring.mvc.view.suffix=

# Configurer Thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# D\u00e9sactiver la gestion d'erreur par d\u00e9faut qui cherche error.jsp
server.error.whitelabel.enabled=false
server.error.path=/error