package com.securityapp.gofundme.model;

public enum AuditAction {
    LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,

    CAMPAIGN_CREATE_ATTEMPT,
    CAMPAIGN_CREATED,
    CAMPAIGN_UPDATE_ATTEMPT,
    CAMPAIGN_UPDATED,
    CAMPAIGN_DELETE_ATTEMPT,
    CAMPAIGN_DELETED,

    DONATION_CREATE_ATTEMPT,
    DONATION_PAYMENT_PENDING,
    DONATION_PAYMENT_SUCCESS,
    DONATION_PAYMENT_FAILED,
    DONATION_PAYMENT_CANCELLED,
    DONATION_CONFIRMED,

    PAYMENT_COMPLETED,

    REPORT_CREATE_ATTEMPT,
    REPORT_CREATED,
    REPORT_FAILED,
    REPORT_UPDATED,
    REPORT_STATUS_CHANGED,

    LIKE_ADDED,
    LIKE_REMOVED,
    DISLIKE_ADDED,
    DISLIKE_REMOVED,

    WITHDRAWAL_REQUEST_ATTEMPT,
    WITHDRAWAL_REQUEST_CREATED,
    WITHDRAWAL_REQUEST_FAILED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,

    ADMIN_ACTION,
    USER_ACTION_ATTEMPT,
    USER_ACTION_SUCCESS,
    USER_ACTION_FAILED
}
